version: '3'

services:
  php:
    build: .
    ports:
     - "8123:80"
     - "4431:443"
    volumes:
     - ./www:/var/www/html
    container_name: php.teco
    links:
     - sqlite3

  sqlite3:
    image: nouchka/sqlite3:latest
    restart: always
    container_name: sqlite.teco
    stdin_open: true
    tty: true
    volumes:
     - ./www/app/db/:/root/db/
