<!DOCTYPE HTML>
<html>
<head>
<title>Teco</title>
<meta charset="utf-8" />

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cerulean/bootstrap.min.css" rel="stylesheet" integrity="sha384-zF4BRsG/fLiTGfR9QL82DrilZxrwgY/+du4p/c7J72zZj+FLYq4zY00RylP9ZjiT" crossorigin="anonymous">

<link href="/assets/css/custom-styles.css" rel="stylesheet">

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-link"></span> Teco</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="https://github.com/efrj/Teco">Fork me on GitHub</a></li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Teco - Encurtador de URL</h1>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <form class="form-inline" id="formShortUrl">
                <div class="form-group">
                    <label class="sr-only">URL</label>
                    <p class="form-control-static">URL</p>
                </div>
                <div class="form-group">
                    <label for="url" class="sr-only">URL</label>
                    <input type="text" class="form-control" id="url" placeholder="http://www.sua-url.com.br">
                </div>
                <button type="submit" class="btn btn-primary">Encurtar URL</button>
            </form>
        </div>
    </div>

    <div class="row new-url">
        <div class="col-md-12">
            <h3>Copie a url encurtada</h3>
            <div class="alert alert-success" role="alert" id="shortUrl"></div>
        </div>
    </div>
</div>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script type="text/javascript" src="/assets/js/custom.js"></script>
</body>
</html>