<!DOCTYPE HTML>
<html lang="pt-br">
<head>
<title>Teco Encurtador de URL</title>
<meta charset="utf-8" />

<meta name="description" content="Teco é um encurtador de url simples e prático">
<meta name="keywords" content="encurtador url">

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cerulean/bootstrap.min.css" rel="stylesheet" integrity="sha384-zF4BRsG/fLiTGfR9QL82DrilZxrwgY/+du4p/c7J72zZj+FLYq4zY00RylP9ZjiT" crossorigin="anonymous">

<script src="https://use.fontawesome.com/f19242b769.js"></script>

<link href="/assets/css/custom-styles.css" rel="stylesheet">

<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-42015485-6', 'auto');
ga('send', 'pageview');

</script>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-link"></span> Teco</a>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="list-group">
                <a href="https://github.com/efrj/Teco" class="list-group-item" target="_blank"><span class="fa fa-github"></span> Projeto no GitHub</a>
            </div>
            <div class="list-group">
                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                <ins class="adsbygoogle"
                     style="display:inline-block;width:300px;height:250px"
                     data-ad-client="ca-pub-3511498162597903"
                     data-ad-slot="4349807852"></ins>
                <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
            </div>
            <div class="list-group">
                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                <ins class="adsbygoogle"
                     style="display:inline-block;width:336px;height:280px"
                     data-ad-client="ca-pub-3511498162597903"
                     data-ad-slot="5486949459"></ins>
                <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
            </div>
        </div>

        <div class="col-md-8">
            <h1>Teco encurtador de URL</h1>
            <hr>
            <form class="form-inline" id="formShortUrl">
                <div class="form-group">
                    <label class="sr-only">URL</label>
                    <p class="form-control-static">Informe a URL para encurtar</p>
                </div>
                <div class="form-group">
                    <label for="url" class="sr-only">URL</label>
                    <input type="text" class="form-control" id="url" placeholder="http://www.sua-url.com.br" required="">
                </div>
                <button type="submit" class="btn btn-primary">Encurtar URL</button>
            </form>
        </div>
        <div class="col-md-8 new-url">
            <h3>Copie a url encurtada</h3>
            <div class="alert alert-success" role="alert" id="shortUrl"></div>
        </div>
        <div class="col-md-8 url-error">
            <h3>Ocorreu um Erro</h3>
            <div class="alert alert-danger" role="alert">
                A url informada é inválida. Informe uma url válida.
            </div>
        </div>

        <div class="col-md-8">
             <script type='text/javascript' src='http://ultimosegundo.ig.com.br/_static/widgets/652171.js' ></script>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <hr>
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Bloco02 -->
            <ins class="adsbygoogle"
                 style="display:block"
                 data-ad-client="ca-pub-3511498162597903"
                 data-ad-slot="6458459858"
                 data-ad-format="auto"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div>
    </div>

    <hr>

    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>&copy;<?=date("Y")?> <strong>Teco encurtador de URL</strong></p>
            </div>
        </div>
    </footer>

</div>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script type="text/javascript" src="/assets/js/custom.js"></script>
</body>
</html>